name: Stock Scanner

on:
  schedule:
    - cron: '30 3 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install yfinance pandas ta requests feedparser

    - name: Run Scanner
      run: python scanner.py
